// GENERATED by scripts/extract-bach.py from the music21 Bach chorale corpus. Do not edit.
// Counts of root-degree moves (row = from degree 1..7, column = to degree 1..7).
export const BACH_CHORALES = {"major": 182, "minor": 186};
export const BACH_MAJOR: number[][] = [[0, 334, 61, 471, 618, 240, 56], [217, 0, 112, 40, 510, 147, 34], [63, 52, 0, 98, 38, 261, 8], [322, 143, 48, 0, 184, 48, 67], [952, 187, 121, 96, 0, 212, 8], [135, 337, 116, 95, 202, 0, 51], [104, 6, 59, 12, 22, 21, 0]];
export const BACH_MINOR: number[][] = [[0, 290, 87, 437, 512, 123, 152], [136, 0, 74, 21, 352, 43, 23], [208, 63, 0, 194, 79, 166, 229], [246, 92, 113, 0, 163, 28, 297], [826, 83, 86, 106, 0, 108, 34], [57, 101, 131, 87, 58, 0, 58], [122, 20, 446, 93, 88, 24, 0]];
