import { describe, expect, it } from 'vitest';
import {
  buildScale, scaleFromPitchClass, scaleNoteNames, SCALES, diatonicChord, diatonicChords,
  chordNoteNames, CHORD_SIZES, pitchClass, degreeLabels, getScaleDef, type ScaleId,
} from '../engine';

/**
 * Expected values below are written by hand from standard music theory —
 * NOT generated by the engine — so they act as an independent check.
 */
const symbols = (root: string, id: ScaleId, size: Parameters<typeof diatonicChords>[1] = 'triad') =>
  diatonicChords(buildScale(root, id), size).map((c) => c.symbol);
const romans = (root: string, id: ScaleId) => diatonicChords(buildScale(root, id)).map((c) => c.roman);

describe('Phase 1 acceptance', () => {
  it('C Dorian, degree 4 → F A C', () => {
    expect(chordNoteNames(diatonicChord(buildScale('C', 'dorian'), 4))).toEqual(['F', 'A', 'C']);
  });
  it('C Dorian, degree 1 → C Eb G', () => {
    expect(chordNoteNames(diatonicChord(buildScale('C', 'dorian'), 1))).toEqual(['C', 'Eb', 'G']);
  });
});

describe('scale spelling', () => {
  const cases: [string, ScaleId, string][] = [
    ['C', 'ionian', 'C D E F G A B'],
    ['C', 'dorian', 'C D Eb F G A Bb'],
    ['C', 'aeolian', 'C D Eb F G Ab Bb'],
    ['C', 'phrygian', 'C Db Eb F G Ab Bb'],
    ['C', 'lydian', 'C D E F# G A B'],
    ['C', 'mixolydian', 'C D E F G A Bb'],
    ['C', 'locrian', 'C Db Eb F Gb Ab Bb'],
    ['C', 'harmonicMinor', 'C D Eb F G Ab B'],
    ['C', 'melodicMinor', 'C D Eb F G A B'],
    ['C', 'phrygianDominant', 'C Db E F G Ab Bb'],
    ['A', 'aeolian', 'A B C D E F G'],
    ['D', 'dorian', 'D E F G A B C'],
    ['F#', 'ionian', 'F# G# A# B C# D# E#'],
    ['Eb', 'dorian', 'Eb F Gb Ab Bb C Db'],
    ['E', 'phrygianDominant', 'E F G# A B C D'],
  ];
  it.each(cases)('%s %s', (root, id, expected) => {
    expect(scaleNoteNames(buildScale(root, id)).join(' ')).toBe(expected);
  });

  it('picks the cleaner enharmonic root (pitch class 1 Locrian → C#, not Db)', () => {
    expect(scaleNoteNames(scaleFromPitchClass(1, 'locrian')).join(' ')).toBe('C# D E F# G A B');
  });
});

describe('diatonic triads', () => {
  it('C major', () => expect(symbols('C', 'ionian')).toEqual(['C', 'Dm', 'Em', 'F', 'G', 'Am', 'B°']));
  it('A minor', () => expect(symbols('A', 'aeolian')).toEqual(['Am', 'B°', 'C', 'Dm', 'Em', 'F', 'G']));
  it('C Dorian', () => expect(symbols('C', 'dorian')).toEqual(['Cm', 'Dm', 'E♭', 'F', 'Gm', 'A°', 'B♭']));
  it('C Lydian', () => expect(symbols('C', 'lydian')).toEqual(['C', 'D', 'Em', 'F♯°', 'G', 'Am', 'Bm']));
  it('C Mixolydian', () => expect(symbols('C', 'mixolydian')).toEqual(['C', 'Dm', 'E°', 'F', 'Gm', 'Am', 'B♭']));
  it('C Phrygian', () => expect(symbols('C', 'phrygian')).toEqual(['Cm', 'D♭', 'E♭', 'Fm', 'G°', 'A♭', 'B♭m']));
  it('C Locrian', () => expect(symbols('C', 'locrian')).toEqual(['C°', 'D♭', 'E♭m', 'Fm', 'G♭', 'A♭', 'B♭m']));
  it('C harmonic minor', () => expect(symbols('C', 'harmonicMinor')).toEqual(['Cm', 'D°', 'E♭+', 'Fm', 'G', 'A♭', 'B°']));
  it('C melodic minor', () => expect(symbols('C', 'melodicMinor')).toEqual(['Cm', 'Dm', 'E♭+', 'F', 'G', 'A°', 'B°']));
  it('C Phrygian dominant', () => expect(symbols('C', 'phrygianDominant')).toEqual(['C', 'D♭', 'E°', 'Fm', 'G°', 'A♭+', 'B♭m']));
});

describe('diatonic 7th chords', () => {
  it('C major', () =>
    expect(symbols('C', 'ionian', '7th')).toEqual(['Cmaj7', 'Dm7', 'Em7', 'Fmaj7', 'G7', 'Am7', 'Bm7♭5']));
  it('C harmonic minor', () =>
    expect(symbols('C', 'harmonicMinor', '7th')).toEqual(['Cm(maj7)', 'Dm7♭5', 'E♭+maj7', 'Fm7', 'G7', 'A♭maj7', 'B°7']));
  it('C melodic minor', () =>
    expect(symbols('C', 'melodicMinor', '7th')).toEqual(['Cm(maj7)', 'Dm7', 'E♭+maj7', 'F7', 'G7', 'Am7♭5', 'Bm7♭5']));
});

describe('extensions', () => {
  it('C Dorian i9 = C Eb G Bb D', () => {
    const c = diatonicChord(buildScale('C', 'dorian'), 1, '9th');
    expect(chordNoteNames(c)).toEqual(['C', 'Eb', 'G', 'Bb', 'D']);
    expect(c.symbol).toBe('Cm7(9)');
  });
  it('Phrygian i gets a ♭9', () => expect(diatonicChord(buildScale('C', 'phrygian'), 1, '9th').symbol).toBe('Cm7(♭9)'));
  it('Lydian I gets a ♯11', () => expect(diatonicChord(buildScale('C', 'lydian'), 1, '11th').symbol).toBe('Cmaj7(9,♯11)'));
  it('13th chord uses all seven notes', () =>
    expect(chordNoteNames(diatonicChord(buildScale('C', 'ionian'), 5, '13th'))).toEqual(['G', 'B', 'D', 'F', 'A', 'C', 'E']));
});

describe('roman numerals (relative to major on the same root)', () => {
  it('C major', () => expect(romans('C', 'ionian')).toEqual(['I', 'ii', 'iii', 'IV', 'V', 'vi', 'vii°']));
  it('C Dorian', () => expect(romans('C', 'dorian')).toEqual(['i', 'ii', '♭III', 'IV', 'v', 'vi°', '♭VII']));
  it('C minor', () => expect(romans('C', 'aeolian')).toEqual(['i', 'ii°', '♭III', 'iv', 'v', '♭VI', '♭VII']));
  it('C harmonic minor', () => expect(romans('C', 'harmonicMinor')).toEqual(['i', 'ii°', '♭III+', 'iv', 'V', '♭VI', 'vii°']));
});

describe('invariants across all 12 roots × all scales × all sizes', () => {
  for (let pc = 0; pc < 12; pc++) {
    for (const def of SCALES) {
      it(`pc ${pc} ${def.id}`, () => {
        const s = scaleFromPitchClass(pc, def.id);
        // 7 distinct letters, correct pitch classes, no double sharps/flats.
        expect(new Set(s.notes.map((n) => n.letter)).size).toBe(7);
        expect(s.pitchClasses).toEqual(def.intervals.map((i) => (pc + i) % 12));
        expect(s.notes.every((n) => Math.abs(n.accidental) <= 1)).toBe(true);
        for (const size of CHORD_SIZES) {
          for (const c of diatonicChords(s, size)) {
            expect(c.pitchClasses.every((p) => s.pitchClasses.includes(p))).toBe(true);
            expect(c.notes.map(pitchClass)).toEqual(c.pitchClasses);
            expect(c.tensions.every((t) => !t.startsWith('?'))).toBe(true);
          }
        }
      });
    }
  }
});

describe('degree labels', () => {
  it('Dorian', () => expect(degreeLabels(getScaleDef('dorian'))).toEqual(['1', '2', '♭3', '4', '5', '6', '♭7']));
  it('Lydian', () => expect(degreeLabels(getScaleDef('lydian'))).toEqual(['1', '2', '3', '♯4', '5', '6', '7']));
});
