"""
Learn chord-to-chord movement from J.S. Bach's 4-part chorales (public domain, music21 corpus).

For each chorale: detect key (major/minor), reduce to one chord per beat, label each chord by the
scale degree of its root (1-7, diatonic roots only), merge repeats, and count degree -> degree moves.
Output: data/bach-transitions.json  { major: 7x7 counts, minor: 7x7 counts, chorales: n }
"""
import json, sys, multiprocessing as mp
from music21 import corpus, roman

def analyze(path):
    try:
        s = corpus.parse(path)
        if len(s.parts) != 4:
            return None
        k = s.analyze('key')
        if k.mode not in ('major', 'minor'):
            return None
        ch = s.chordify()
        degrees = []
        for c in ch.recurse().getElementsByClass('Chord'):
            if c.offset % 1 != 0 or len(c.pitches) < 3:
                continue  # on-beat, full chords only (skips passing tones)
            rn = roman.romanNumeralFromChord(c, k)
            if rn.frontAlterationAccidental is not None:
                continue  # chromatic root: not a diatonic degree
            d = rn.scaleDegree
            if not degrees or degrees[-1] != d:
                degrees.append(d)
        return (k.mode, degrees)
    except Exception:
        return None

if __name__ == '__main__':
    paths = [p for p in corpus.getComposer('bach') if 'bwv' in str(p).lower()]
    with mp.Pool(max(2, mp.cpu_count())) as pool:
        results = [r for r in pool.map(analyze, paths, chunksize=4) if r]
    out = {'major': [[0] * 7 for _ in range(7)], 'minor': [[0] * 7 for _ in range(7)], 'chorales': {'major': 0, 'minor': 0}}
    for mode, degs in results:
        out['chorales'][mode] += 1
        for a, b in zip(degs, degs[1:]):
            out[mode][a - 1][b - 1] += 1
    json.dump(out, open(sys.argv[1], 'w'), indent=1)
    print('chorales', out['chorales'])

# Also emit a TypeScript module so the engine can use the data without file access at runtime.
if __name__ == '__main__':
    ts = ('// GENERATED by scripts/extract-bach.py from the music21 Bach chorale corpus. Do not edit.\n'
          '// Counts of root-degree moves (row = from degree 1..7, column = to degree 1..7).\n'
          f"export const BACH_CHORALES = {json.dumps(out['chorales'])};\n"
          f"export const BACH_MAJOR: number[][] = {json.dumps(out['major'])};\n"
          f"export const BACH_MINOR: number[][] = {json.dumps(out['minor'])};\n")
    open('engine/bach-data.ts', 'w').write(ts)
